/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.awt.Color;
import Clase.*;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private TextPrompt PlaceHolderCliente, PlaceHolderProducto;
    private VariableLocal conexion; //objeto para la conexion a la BD
    private String[] titulosCliente = {"ID", "Nombre", "Nit", "Direccion", "Saldo"},
            titulosProducto = {"ID", "Nombre", "Existencia", "Precio"}; //Encabezados de las tablas
    private Cliente cliente;//objeto de cliente
    private Producto producto;
    private Reloj reloj;

    public VentanaPrincipal() {
        //quita los botones de cerrar y minimizar
        this.setUndecorated(true);
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        PlaceHolderCliente = new TextPrompt("Buscar Cliente", txtBuscarCliente);
        PlaceHolderProducto = new TextPrompt("Buscar Producto", txtBuscarProducto);
        conexion = new VariableLocal();
        cliente = new Cliente();
        producto = new Producto();
        reloj = new Reloj(labelReloj); //Instanciamos el reloj
        reloj.hilo1.start();//Lo encendemos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PnlSuperior = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelMinimizarVentana = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panelCerrarVentana = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelReloj = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PnlLatIzquierdo = new javax.swing.JPanel();
        btnProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRespaldo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlCentral = new javax.swing.JPanel();
        PnlProducto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        comboFormaProducto = new javax.swing.JComboBox<>();
        comboOrdenProducto = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PnlRespaldo = new javax.swing.JPanel();
        PnlCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JPanel();
        labelBuscarCliente = new javax.swing.JLabel();
        comboForma = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        PnlSuperior.setBackground(new java.awt.Color(29, 45, 80));

        jPanel5.setBackground(new java.awt.Color(29, 45, 80));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/netbeans_103238.png"))); // NOI18N

        panelMinimizarVentana.setBackground(new java.awt.Color(29, 45, 80));
        panelMinimizarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccionPanelMC(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaouseEntrarMC(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaouseSalirMC(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/window_minimize_icon_138009.png"))); // NOI18N

        javax.swing.GroupLayout panelMinimizarVentanaLayout = new javax.swing.GroupLayout(panelMinimizarVentana);
        panelMinimizarVentana.setLayout(panelMinimizarVentanaLayout);
        panelMinimizarVentanaLayout.setHorizontalGroup(
            panelMinimizarVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMinimizarVentanaLayout.setVerticalGroup(
            panelMinimizarVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCerrarVentana.setBackground(new java.awt.Color(29, 45, 80));
        panelCerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccionPanelMC(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaouseEntrarMC(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaouseSalirMC(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/windowclose_104378.png"))); // NOI18N

        javax.swing.GroupLayout panelCerrarVentanaLayout = new javax.swing.GroupLayout(panelCerrarVentana);
        panelCerrarVentana.setLayout(panelCerrarVentanaLayout);
        panelCerrarVentanaLayout.setHorizontalGroup(
            panelCerrarVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCerrarVentanaLayout.setVerticalGroup(
            panelCerrarVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(497, Short.MAX_VALUE)
                .addComponent(labelReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(panelMinimizarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMinimizarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlSuperiorLayout = new javax.swing.GroupLayout(PnlSuperior);
        PnlSuperior.setLayout(PnlSuperiorLayout);
        PnlSuperiorLayout.setHorizontalGroup(
            PnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlSuperiorLayout.setVerticalGroup(
            PnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(PnlSuperior, java.awt.BorderLayout.PAGE_START);

        PnlLatIzquierdo.setBackground(new java.awt.Color(19, 59, 92));

        btnProducto.setBackground(new java.awt.Color(19, 59, 92));
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventoClic(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntradaMause(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalidaMause(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto");

        javax.swing.GroupLayout btnProductoLayout = new javax.swing.GroupLayout(btnProducto);
        btnProducto.setLayout(btnProductoLayout);
        btnProductoLayout.setHorizontalGroup(
            btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnProductoLayout.setVerticalGroup(
            btnProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRespaldo.setBackground(new java.awt.Color(19, 59, 92));
        btnRespaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventoClic(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntradaMause(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalidaMause(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Respaldo");

        javax.swing.GroupLayout btnRespaldoLayout = new javax.swing.GroupLayout(btnRespaldo);
        btnRespaldo.setLayout(btnRespaldoLayout);
        btnRespaldoLayout.setHorizontalGroup(
            btnRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRespaldoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(48, 48, 48))
        );
        btnRespaldoLayout.setVerticalGroup(
            btnRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnCliente.setBackground(new java.awt.Color(19, 59, 92));
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventoClic(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntradaMause(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalidaMause(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");

        javax.swing.GroupLayout btnClienteLayout = new javax.swing.GroupLayout(btnCliente);
        btnCliente.setLayout(btnClienteLayout);
        btnClienteLayout.setHorizontalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClienteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnClienteLayout.setVerticalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PnlLatIzquierdoLayout = new javax.swing.GroupLayout(PnlLatIzquierdo);
        PnlLatIzquierdo.setLayout(PnlLatIzquierdoLayout);
        PnlLatIzquierdoLayout.setHorizontalGroup(
            PnlLatIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRespaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlLatIzquierdoLayout.setVerticalGroup(
            PnlLatIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLatIzquierdoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlLatIzquierdo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlLatIzquierdo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        PnlCentral.setLayout(new java.awt.CardLayout());

        PnlProducto.setBackground(new java.awt.Color(30, 95, 116));

        tablaProducto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaProducto.setForeground(new java.awt.Color(0, 0, 0));
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaProducto.setGridColor(new java.awt.Color(29, 45, 80));
        tablaProducto.setRowHeight(20);
        tablaProducto.setSelectionBackground(new java.awt.Color(252, 218, 183));
        tablaProducto.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaProducto);

        txtBuscarProducto.setBackground(new java.awt.Color(19, 59, 92));
        txtBuscarProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarProducto.setBackground(new java.awt.Color(30, 95, 116));
        btnBuscarProducto.setForeground(new java.awt.Color(30, 95, 116));
        btnBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcccionPanelesBusqueda(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntradaMousePanelBusqueda(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalidaMousePanelBusqueda(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/find_search_locate_6201.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarProductoLayout = new javax.swing.GroupLayout(btnBuscarProducto);
        btnBuscarProducto.setLayout(btnBuscarProductoLayout);
        btnBuscarProductoLayout.setHorizontalGroup(
            btnBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
        );
        btnBuscarProductoLayout.setVerticalGroup(
            btnBuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        comboFormaProducto.setBackground(new java.awt.Color(19, 59, 92));
        comboFormaProducto.setForeground(new java.awt.Color(255, 255, 255));
        comboFormaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre" }));

        comboOrdenProducto.setBackground(new java.awt.Color(19, 59, 92));
        comboOrdenProducto.setForeground(new java.awt.Color(255, 255, 255));
        comboOrdenProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Predeterminada", "Mayor existencia - Menor existencia", "Mayor Precio - Menor precio", "Menor existencia - Mayor existencia ", "Menor precio - Mayor Precio " }));

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Forma de busqueda");

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Odern de la tabla");

        jPanel4.setBackground(new java.awt.Color(30, 95, 116));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/business_inventory_maintenance_product_box_boxes_2326.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );

        jLabel13.setBackground(new java.awt.Color(187, 187, 187));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setText("PRODUCTO");

        javax.swing.GroupLayout PnlProductoLayout = new javax.swing.GroupLayout(PnlProducto);
        PnlProducto.setLayout(PnlProductoLayout);
        PnlProductoLayout.setHorizontalGroup(
            PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlProductoLayout.createSequentialGroup()
                .addGroup(PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlProductoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboOrdenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFormaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(41, 41, 41)
                        .addGroup(PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnlProductoLayout.createSequentialGroup()
                                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlProductoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(28, 28, 28)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PnlProductoLayout.setVerticalGroup(
            PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlProductoLayout.createSequentialGroup()
                .addGroup(PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlProductoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboOrdenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(PnlProductoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                .addGroup(PnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlProductoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboFormaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        PnlCentral.add(PnlProducto, "card3");

        PnlRespaldo.setBackground(new java.awt.Color(30, 95, 116));

        javax.swing.GroupLayout PnlRespaldoLayout = new javax.swing.GroupLayout(PnlRespaldo);
        PnlRespaldo.setLayout(PnlRespaldoLayout);
        PnlRespaldoLayout.setHorizontalGroup(
            PnlRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        PnlRespaldoLayout.setVerticalGroup(
            PnlRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        PnlCentral.add(PnlRespaldo, "card4");

        PnlCliente.setBackground(new java.awt.Color(30, 95, 116));

        tablaCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaCliente.setForeground(new java.awt.Color(0, 0, 0));
        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaCliente.setGridColor(new java.awt.Color(29, 45, 80));
        tablaCliente.setRowHeight(20);
        tablaCliente.setSelectionBackground(new java.awt.Color(252, 218, 183));
        tablaCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCliente);

        txtBuscarCliente.setBackground(new java.awt.Color(19, 59, 92));
        txtBuscarCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuscarCliente.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarCliente.setBackground(new java.awt.Color(30, 95, 116));
        btnBuscarCliente.setForeground(new java.awt.Color(30, 95, 116));
        btnBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcccionPanelesBusqueda(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntradaMousePanelBusqueda(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalidaMousePanelBusqueda(evt);
            }
        });

        labelBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/find_search_locate_6201.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarClienteLayout = new javax.swing.GroupLayout(btnBuscarCliente);
        btnBuscarCliente.setLayout(btnBuscarClienteLayout);
        btnBuscarClienteLayout.setHorizontalGroup(
            btnBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBuscarClienteLayout.setVerticalGroup(
            btnBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        comboForma.setBackground(new java.awt.Color(19, 59, 92));
        comboForma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboForma.setForeground(new java.awt.Color(255, 255, 255));
        comboForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "NIT" }));

        comboTipo.setBackground(new java.awt.Color(19, 59, 92));
        comboTipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboTipo.setForeground(new java.awt.Color(255, 255, 255));
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Deudores", "Sin deuda" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Tipo Cliente");

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Forma de busqueda");

        jPanel2.setBackground(new java.awt.Color(30, 95, 116));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/customer_person_people_man_user_client_1629 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(187, 187, 187));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setText("CLIENTE");

        javax.swing.GroupLayout PnlClienteLayout = new javax.swing.GroupLayout(PnlCliente);
        PnlCliente.setLayout(PnlClienteLayout);
        PnlClienteLayout.setHorizontalGroup(
            PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlClienteLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlClienteLayout.createSequentialGroup()
                        .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlClienteLayout.createSequentialGroup()
                                .addComponent(comboForma, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addGroup(PnlClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        PnlClienteLayout.setVerticalGroup(
            PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlClienteLayout.createSequentialGroup()
                .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        PnlCentral.add(PnlCliente, "card2");

        jPanel1.add(PnlCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CargarTabla(String consulta, int tipoTabla) {
        switch (tipoTabla) {
            case 0:
                conexion.conexionMySQL.llenarTabla(titulosCliente, tablaCliente, consulta);
                txtBuscarCliente.setText("");
                break;
            case 1:
                conexion.conexionMySQL.llenarTabla(titulosProducto, tablaProducto, consulta);
                txtBuscarProducto.setText("");
                break;
        }

    }

    //Evento a la hora de hacer un click en los paneles del lateral izquierdo
    private void EventoClic(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventoClic
        if (evt.getSource() == btnCliente) {
            PnlCliente.setVisible(true);
            PnlRespaldo.setVisible(false);
            PnlProducto.setVisible(false);
        }
        if (evt.getSource() == btnProducto) {
            PnlCliente.setVisible(false);
            PnlRespaldo.setVisible(false);
            PnlProducto.setVisible(true);
        }
        if (evt.getSource() == btnRespaldo) {
            PnlCliente.setVisible(false);
            PnlRespaldo.setVisible(true);
            PnlProducto.setVisible(false);
        }

    }//GEN-LAST:event_EventoClic
//Entrada del cursor a los paneles laterales a la izquierda
    private void EntradaMause(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaMause
        if (evt.getSource() == btnCliente) {
            btnCliente.setBackground(new Color(252, 218, 183));
        }
        if (evt.getSource() == btnProducto) {
            btnProducto.setBackground(new Color(252, 218, 183));
        }
        if (evt.getSource() == btnRespaldo) {
            btnRespaldo.setBackground(new Color(252, 218, 183));
        }

    }//GEN-LAST:event_EntradaMause
//Salida del cursor de los paneles laterales a la izquierda
    private void SalidaMause(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidaMause
        if (evt.getSource() == btnCliente) {
            btnCliente.setBackground(new Color(19, 59, 92));
        }
        if (evt.getSource() == btnProducto) {
            btnProducto.setBackground(new Color(19, 59, 92));
        }
        if (evt.getSource() == btnRespaldo) {
            btnRespaldo.setBackground(new Color(19, 59, 92));
        }

    }//GEN-LAST:event_SalidaMause


    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed
//Accion de los "Botones" de buscar en alguna tabla cuando el cursor esta sobre ellos
    private void EntradaMousePanelBusqueda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaMousePanelBusqueda
        if (evt.getSource() == btnBuscarCliente) {
            btnBuscarCliente.setBackground(new Color(252, 218, 183));
        }
        if (evt.getSource() == btnBuscarProducto) {
            btnBuscarProducto.setBackground(new Color(252, 218, 183));

        }
    }//GEN-LAST:event_EntradaMousePanelBusqueda
//Accion con respecto a los "Botones " de buscar en las tablas de cliente y producto
    private void AcccionPanelesBusqueda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcccionPanelesBusqueda
        String consulta = "";
        int tabla = -1; //indicara en el metodo cargarTabla que tabla y que encabezados debera de mandar a llenarTabla
        if (evt.getSource() == btnBuscarCliente) {
            System.out.println("entro cliente");
            consulta = cliente.getConsulta(comboTipo.getSelectedIndex(), comboForma.getSelectedIndex(), txtBuscarCliente.getText());
            tabla = 0;
        }
        if (evt.getSource() == btnBuscarProducto) {
            System.out.println("entro");
            consulta = producto.getConsulta(comboFormaProducto.getSelectedIndex(), comboOrdenProducto.getSelectedIndex(), txtBuscarProducto.getText());
            tabla = 1;
        }
        CargarTabla(consulta, tabla);
    }//GEN-LAST:event_AcccionPanelesBusqueda
//Accion de los "Botones" de busqueda cuando el cursor ya no esta sobre ellos
    private void SalidaMousePanelBusqueda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidaMousePanelBusqueda
        if (evt.getSource() == btnBuscarCliente) {
            btnBuscarCliente.setBackground(new Color(30, 95, 116));

        }
        if (evt.getSource() == btnBuscarProducto) {
            btnBuscarProducto.setBackground(new Color(30, 95, 116));
        }
    }//GEN-LAST:event_SalidaMousePanelBusqueda
//Accion de los "Botones" cerrar y minimizar 
    private void AccionPanelMC(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccionPanelMC
        if (evt.getSource() == panelCerrarVentana) {
            System.exit(0);

        }
        if (evt.getSource() == panelMinimizarVentana) {
            this.setState(Frame.ICONIFIED);
        }
    }//GEN-LAST:event_AccionPanelMC
//Accion de los "Botones" cerrrar y minimizar cuando el cursor esta sobre ellos 
    private void MaouseEntrarMC(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaouseEntrarMC
        if (evt.getSource() == panelCerrarVentana) {
            panelCerrarVentana.setBackground(new Color(205, 10, 10));

        }
        if (evt.getSource() == panelMinimizarVentana) {
            panelMinimizarVentana.setBackground(new Color(253, 219, 58));
        }
    }//GEN-LAST:event_MaouseEntrarMC
//Accion de los "Botones" cuando ya no esta sobre ellos
    private void MaouseSalirMC(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaouseSalirMC
        if (evt.getSource() == panelCerrarVentana) {
            panelCerrarVentana.setBackground(new Color(29, 45, 80));

        }
        if (evt.getSource() == panelMinimizarVentana) {
            panelMinimizarVentana.setBackground(new Color(29, 45, 80));
        }
    }//GEN-LAST:event_MaouseSalirMC

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlCentral;
    private javax.swing.JPanel PnlCliente;
    private javax.swing.JPanel PnlLatIzquierdo;
    private javax.swing.JPanel PnlProducto;
    private javax.swing.JPanel PnlRespaldo;
    private javax.swing.JPanel PnlSuperior;
    private javax.swing.JPanel btnBuscarCliente;
    private javax.swing.JPanel btnBuscarProducto;
    private javax.swing.JPanel btnCliente;
    private javax.swing.JPanel btnProducto;
    private javax.swing.JPanel btnRespaldo;
    private javax.swing.JComboBox<String> comboForma;
    private javax.swing.JComboBox<String> comboFormaProducto;
    private javax.swing.JComboBox<String> comboOrdenProducto;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBuscarCliente;
    private javax.swing.JLabel labelReloj;
    private javax.swing.JPanel panelCerrarVentana;
    private javax.swing.JPanel panelMinimizarVentana;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarProducto;
    // End of variables declaration//GEN-END:variables
}
